### ISSUE TITLE
Videos from Dev meeting

### ISSUE THREAD

**Issue by jonnycrunch** [ipfs/developer-meetings#42]
What is the status of the dev meeting videos?

**Comment by meiqimichelle** [comment]
@jonnycrunch we hired a great video project manager to help with this and other video-related work -- @doctorrobinson . I know he's been pushing this so I'll let him provide the latest (but he's also been getting up to speed on all things PL -- so fire hose time!)

**Comment by mib-kd743naq** [comment]
@doctorrobinson, @meiqimichelle ping! :stuck_out_tongue_winking_eye:

**Comment by doctorrobinson** [comment]
Hey Jonny, I'm sorry for the long radio silence. This is nearly finished and being tracked in Protocol Labs’ [internal video project management repo](https://github.com/protocol/video/issues/1). I will report back here when they're done, but expect to see an email hit your inbox right after the holidays with links to the videos you were in for approval, then out to the greater world shortly after.
