### ISSUE TITLE
Should we pay for a professional livestream of the dev meetings?

### ISSUE THREAD

**Issue by flyingzumwalt** [ipfs/developer-meetings#8]
The facts
- We will be recording many of the sessions and will post those recordings online a few days after the meetings
- Paying the A/V team to run a live stream is feasible, but would cost money 
- We're not sure how many people would actually watch the live stream rather than waiting a few days to see the recordings

Another twist:  Some people are hoping to live stream the conference over IPFS using https://github.com/tomeshnet/ipfs-live-streaming/ -- If we want to do that, we're effectively asking the AV team to do a live stream because we're asking them to deal with the overhead of piping everything straight to the internet, so we would probably end up paying them the same amount. (If anythng we're asking them to do more work by using our experimental stuff!) It would also be good to have a non-ipfs stream as a fallback if the experimental p2p streaming has glitches. 

I feel inclined to save the money and wait to live stream at IPFS conf, when the content will be better for live streaming and the ipfs-live-streaming will have been tested and used in production multiple times. But I can be swayed to give it a green light if anyone wants to make the case for the benefit of paying for it.

**Comment by djdv** [comment]
>I feel inclined to save the money and wait to live stream at IPFS conf, when the content will be better for live streaming and the ipfs-live-streaming will have been tested and used in production multiple times. 

No strong opinion, but I agree with this. Given that the next conf will have streaming in mind while the current may not. The current conf would be a good test with stream-success as a bonus but not a requirement.

**Comment by Stebalien** [comment]
I agree on waiting. We discuss up sensitive issues (security, moral, etc.) and I'd like people to be able to speak freely knowing that they can ask for something to be edited out.

**Comment by flyingzumwalt** [comment]
Thanks for chiming in. We'll skip it!
